In [1]:
import numpy as np
import pandas as pd
import datetime

In [3]:
#指定各列数据类型，节省内存
column_types = {
    'instance_id':'uint64',
    'item_id':'uint64',
    'item_category_list':'object',
    'item_property_list':'object',
    'item_brand_id':'uint64',
    'item_city_id':'uint64',
    'item_price_level':'uint8',
    'item_sales_level':'uint8',
    'item_collected_level':'uint8',
    'item_pv_level':'uint8',
    'user_id':'uint64',
    'user_gender_id':'category',
    'user_age_level':'uint16',
    'user_occupation_id':'category',
    'user_star_level':'uint16',
    'context_id':'uint64',
    'context_page_id':'uint16',
    'predict_category_property':'object',
    'shop_id':'uint64',
    'shop_review_num_level':'uint8',
    'shop_review_positive_rate':'float32',
    'shop_star_level':'uint16',
    'shop_score_service':'float32',
    'shop_score_delivery':'float32',
    'context_timestamp':'uint32',
    'shop_score_description':'float32',
    'is_trade':'category'
}

In [21]:
df_train=pd.read_csv('round1_ijcai_18_train_20180301.txt',sep=' ',\
                     dtype=column_types,parse_dates=['context_timestamp'],date_parser=datetime.datetime.fromtimestamp)

In [24]:
df_train.head()

,instance_id,item_id,item_category_list,item_property_list,item_brand_id,item_city_id,item_price_level,item_sales_level,item_collected_level,item_pv_level,...,context_page_id,predict_category_property,shop_id,shop_review_num_level,shop_review_positive_rate,shop_star_level,shop_score_service,shop_score_delivery,shop_score_description,is_trade
0,108641074714126964,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4006,5799347067982556520:-1;509660095530134768:-1;5...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
1,5754713551599725161,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
2,842679481291040981,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4001,5799347067982556520:5131280576272319091;725801...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
3,937088850059189027,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4016,509660095530134768:-1;5799347067982556520:-1;7...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0
4,7975697065017708072,3412720377098676069,7908382889764677758;5799347067982556520,2072967855524022579;5131280576272319091;263639...,1975590437749032870,3948283326616421003,3,3,4,14,...,4001,5799347067982556520:9172976955054793469;790838...,6765930309048922341,4,1.0,5002,1.0,1.0,1.0,0

In [1]:
#df_train序列化
import pickle
def to_file(df,filename):
    with open(filename,'wb') as f:
        pickle.dump(df,f)

def from_file(filename):
    with open(filename,'rb') as f:
        return pickle.load(f)

In [91]:
#提取9月22号到24号的数据到训练集
df_3_train = df_train[list(df_train['context_timestamp'].map(lambda x:True if datetime.datetime.fromtimestamp(1537545600)<x<datetime.datetime.fromtimestamp(1537804799) else False))]

In [2]:
df_train=from_file('../data/train01.pkl')